### ISSUE TITLE
Transfering to Julia-Embedded?

### ISSUE THREAD

**Issue by aminya** [tshort/StaticCompiler.jl#1]
@tshort 
Nice package! 

This seems very useful for [Julia-Embedded](https://github.com/Julia-Embedded).  I  already made a mirror fork there.  If you like, you can transfer it there

**Comment by ihnorton** [comment]
@aminya FYI there is already a JuliaEmbedded organization: https://github.com/JuliaEmbedded

(it’s a little strange to be opening up all of these transfer requests out of the blue. Organizations usually come about more organically and via existing collaboration)

**Comment by aminya** [comment]
@ihnorton FYI, @tshort is already a member of https://github.com/Julia-Embedded, and he has discussed these there https://github.com/Julia-Embedded/Julia-Embedded-Master/issues/1, and here https://discourse.julialang.org/t/bring-julia-code-to-embedded-hardware-arm/19979/27. 
BTW, blue is my favorite color. 😕

**Comment by tshort** [comment]
It's probably too early to move it to an organization. It's limited and experimental right now. Feel free to play with it and provide feedback or PRs. Eventually, if it "works" and folks are using it, we can move it to an organization.

**Comment by tshort** [comment]
I'll leave the issue open as a reminder that moving to an organization is an eventual goal.

**Comment by tshort** [comment]
@ihnorton makes a good point on JuliaEmbedded and Julia-Embedded. Seems like an opportunity to collaborate and consolidate.

**Comment by aminya** [comment]
I emailed the owner and I created an issue one month ago regarding merging. I got no answer...
https://github.com/JuliaEmbedded/DigitalArithmetic.jl/issues/1

**Comment by ihnorton** [comment]
My mistake, apparently the repositories there are *also* empty.
