### ISSUE TITLE
Warn when compiled functions contain hard-coded pointers

### ISSUE THREAD

**Issue by brenhinkeller** [tshort/StaticCompiler.jl#103]
This should probably be a warning rather than a hard error for now, but it would be very useful to know, and I think (?) it may be possible to check for this using LLVM?

**Comment by brenhinkeller** [comment]
Inspired by #101

**Comment by MasonProtter** [comment]
I'd also like to just straight up throw an error if I find things like `jl_throw_generic` in the LLVM for standalone compiled code.

**Comment by brenhinkeller** [comment]
Looks like this was implemented in #146!
