### ISSUE TITLE
compile_shlib gives symbol lookup error

### ISSUE THREAD

**Issue by zornsllama** [tshort/StaticCompiler.jl#111]
Hi,

I was trying to replicate the example in the documentation for `compile_shlib.` On running the `compile_shlib` function, I get a symbol lookup error:

```
julia> compile_shlib(test, (Int,))

~/.julia/artifacts/9f98f3ddf523da9c41e1e5f66b7d0176a008d4f7/tools/clang: symbol lookup error: ~/.julia/artifacts/9f98f3ddf523da9c41e1e5f66b7d0176a008d4f7/tools/clang: undefined symbol: LLVMI
nitializeAVRTargetInfo, version JL_LLVM_14.0
```

This was in Julia 1.9.0-rc2. Any help resolving this issue would be greatly appreciated!

**Comment by tshort** [comment]
That's the same issue hit in #110. According to [this](https://github.com/JuliaPackaging/Yggdrasil/issues/6615#issuecomment-1516460596), it'll work when Julia 1.9.0 comes out.

In the meantime, you can use Julia v1.8.5, or with 1.9.0rc2, you can pin LLVM_jll to v14.0.5.
