### ISSUE TITLE
Depend on StaticTools.jl ?

### ISSUE THREAD

**Issue by MasonProtter** [tshort/StaticCompiler.jl#115]
For the sake of convenience, it seems like we should maybe just depend on, and re-export StaticTools.jl? Any thoughts for or against this?

**Comment by tshort** [comment]
We already depend on it. I don't have a preference on re-exporting.

**Comment by MasonProtter** [comment]
Oh, yeah, I guess that happened with all the error stuff. @brenhinkeller any thoughts? 

I guess we could also just tell people that they can do
```julia
using StaticCompiler.StaticTools
```
if they want access to the goodies.

**Comment by brenhinkeller** [comment]
Oh good question.. either works for me!
