### ISSUE TITLE
jlrun is not consistent on different OS

### ISSUE THREAD

**Issue by aminya** [tshort/StaticCompiler.jl#12]
Linux - 3 of them fail
https://travis-ci.com/aminya/StaticCompiler.jl/jobs/269898292#L222
MacOS - 1 of them fails
https://travis-ci.com/aminya/StaticCompiler.jl/jobs/269898293#L188

So this part of the code seems to be highly dependent on the OS.

**Comment by tshort** [comment]
Yeah. Not sure what to do about this. It's another sign that `@jlrun` isn't ready for the main code.
