### ISSUE TITLE
Bound-check and panic somehow?

### ISSUE THREAD

**Issue by PallHaraldsson** [tshort/StaticCompiler.jl#127]
See at: https://github.com/brenhinkeller/StaticTools.jl/issues/48

The issue belong rather here I think. I don't know how to migrate, only copy text. If it doesn't blong here, then simply close, if it does migrate the other or close it and continue here.

**Comment by brenhinkeller** [comment]
I think that can stay on the StaticTools side — the one thing that could be done on this side is if anyone wants to add more default ***@***.***_override` statements for other common errors

**Comment by MasonProtter** [comment]
I'm on Pall's side. StaticTools.jl should just emit a bounds error, and we should intercept the creation and throwing of that bounds error in StaticCompiler

**Comment by brenhinkeller** [comment]
Ok, I think we can close this here, but PRs welcome on the StaticTools side
