### ISSUE TITLE
Running external programs

### ISSUE THREAD

**Issue by Thomas008** [tshort/StaticCompiler.jl#165]
Is it possible to call external programs in a code that can be staticcally compiled with StaticCompiler (e.g. a shell script test.sh)?

**Comment by brenhinkeller** [comment]
It might be slightly cursed, but you should probably be able `ccall` the libc `system` function

**Comment by brenhinkeller** [comment]
Or if `ccall`/`@ccall` don't wont to compile then I suppose `StaticTools.@symbolcall` should definitely work (though even more cursed), e.g.
```
julia> using StaticTools

julia> function sys(s)
           @symbolcall system(pointer(s)::Ptr{UInt8})::Int
       end
sys (generic function with 1 method)

julia> sys(c"pwd")
/Users/cbkeller
0
```

**Comment by Thomas008** [comment]
Thank you! This works perfect!
