### ISSUE TITLE
Julia PR  #33955

### ISSUE THREAD

**Issue by AriMKatz** [tshort/StaticCompiler.jl#30]
https://github.com/JuliaLang/julia/pull/33955

"This allows selective overriding of the compilation pipeline through
multiple dispatch, enabling projects like XLA.jl to maintain separate
inference caches, inference algorithms or heuristic algorithms while
inferring and lowering code."

Seems like it could be of use to this package.

**Comment by AriMKatz** [comment]
Sorry, I see you already mentioned this.

**Comment by tshort** [comment]
That's a great one to keep in eye on. Another interesting one is https://github.com/JuliaLang/julia/pull/35015.

**Comment by AriMKatz** [comment]
Yup. Exciting times
