### ISSUE TITLE
undefined reference to `jl_n_threads' on Windows

### ISSUE THREAD

**Issue by aminya** [tshort/StaticCompiler.jl#6]
When running test/ccalls.jl
```
test.o: In function `call':

C:\Users\travis\.julia\packages\Cassette\YCOeN\src/context.jl:447: undefined reference to `jl_n_threads'

collect2.exe: error: ld returned 1 exit status
```
https://travis-ci.com/tshort/StaticCompiler.jl/jobs/261775338#L137

**Comment by aminya** [comment]
Caused by `unsafe_load()` in `f()`

**Comment by aminya** [comment]
By removing `unsafe_load()` we get:
![image](https://user-images.githubusercontent.com/16418197/69900403-80e7e980-1338-11ea-85c9-d98a6704ef45.png)

**Comment by aminya** [comment]
Happens when the shell command is run.

**Comment by tshort** [comment]
Interesting. I thought `jl_n_threads` would be universal. There's probably another function that will suffice for this test. Will have to look.

**Comment by aminya** [comment]
It is not just this one. Running 
test/globals.jl
gives a lot of similar errors:
![image](https://user-images.githubusercontent.com/16418197/69900972-3bc7b580-1340-11ea-9976-7bd747a1bbb5.png)

**Comment by tshort** [comment]
Interesting. Must be a deeper bug. I can look, but probably not for a couple of days.

**Comment by tshort** [comment]
I think the problem is that the macro `jlrun` cannot find `libjulia`. It should try to link to `lib/libjulia.dll.a`. It has a different name on Linux (and probably MacOS, too). [This line](https://github.com/tshort/StaticCompiler.jl/blob/a3c946c411116e12fd559592d7b405807974d618/test/jlrun.jl#L45) probably needs to splice in a different library name, depending on the platform.

**Comment by aminya** [comment]
I addressed this in the PR now, but still doesn't work.

**Comment by tshort** [comment]
I played around with this locally for a bit and couldn't find a gcc command that would work.

**Comment by aminya** [comment]
There are some stuff to test from the documentation:
https://docs.julialang.org/en/v1/manual/embedding/#

**Comment by tshort** [comment]
I hate compiling on Windows. Looks like it might be an ordering issue (hint [here](http://www.mingw.org/wiki/The_linker_consistently_giving_undefined_references)). So, the compile statement needs to have `test.o -ljulia.dll` instead of `-ljulia.dll test.o`.

**Comment by aminya** [comment]
![image](https://user-images.githubusercontent.com/16418197/69907367-b375fe80-1399-11ea-8152-2888380ee12e.png)
Yay, I think it is solved

**Comment by aminya** [comment]
Closed by https://github.com/aminya/StaticCompiler.jl/commit/64ef80b5bd407403fd77b7319c53120b239eab46
