### ISSUE TITLE
Automatic gcc/clang compiler installation

### ISSUE THREAD

**Issue by aminya** [tshort/StaticCompiler.jl#7]
Provide gcc/clang compiler through JIL packages or BinaryProvider or BinaryBuilder.

https://github.com/JuliaPackaging/Yggdrasil/issues/17

Discussion in Slack:
https://julialang.slack.com/archives/C674ELDNX/p1575110827223000
https://julialang.slack.com/archives/CB8A1RNCE/p1575316088173300

> For more robust compiling across platforms, PackageCompilerX is a good place to look.

**Comment by tshort** [comment]
Here's a try that Kristoffer made for Clang: https://github.com/KristofferC/Clang_jll.jl

According to discussions on the static_compilation channel on Slack, he ran into problems on Windows.

**Comment by aminya** [comment]
Matlab automatically installs MinGW for Windows over the internet. The [PR]((https://github.com/tshort/StaticCompiler.jl/commit/05abce4f4094c48b75f3d8cf468665e735c70dcf) ) I made was using this toolchain

**Comment by tshort** [comment]
LLVM/Clang is getting close now (https://github.com/JuliaPackaging/Yggdrasil/pull/296). It is still failing on some platforms, though.

**Comment by aminya** [comment]
LLVM recipe is merged. Should we use it now?

**Comment by aminya** [comment]
There is no Artifacts.toml yet
https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/issues/1

**Comment by tshort** [comment]
When it's ready, it's worth trying.

One tricky thing might be pulling the same version of LLVM that Julia is currently running. (And for WebAssembly, the higher version of LLVM, the better.)

**Comment by aminya** [comment]
So Artifacts are up:
https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/

**Comment by aminya** [comment]
@tshort is the new PackageCompiler (formerly known as X) useful for StaticCompiler?

**Comment by tshort** [comment]
The new PackageCompiler is an alternative approach to doing the same thing. Some comparisons:

PackageCompiler
* Mature
* Works with a wide range of code
* Huge library output (needs tree shaking to reduce size)
* Can't cross compile (I think)

StaticCompiler
* Immature
* Works with a narrow range of code
* Small output
* Can cross compile

**Comment by aminya** [comment]
Yes, so can't we reuse some code from PackageCompiler to enhance the StaticCompiler? At least, PackageCompiler now installs `gcc` on Windows automatically.

**Comment by tshort** [comment]
Should be possible. We're already using some of their code.
