### ISSUE TITLE
Linux undefined reference to `llvm::DominatorTree...`

### ISSUE THREAD

**Issue by aminya** [tshort/StaticCompiler.jl#8]
A lot of undefined references happens on Linux, but not on Windows

https://travis-ci.com/tshort/StaticCompiler.jl/jobs/261973212#L434

**Comment by jpsamaroo** [comment]
Taking a guess, given that a lot of very core LLVM symbols are missing: ld is probably failing to find LLVM altogether. I seem to recall that Windows libraries go in `bin/` instead of `lib/`? If so, your `-L/home/travis/julia/lib` and `-rpath,/home/travis/julia/lib` arguments are probably wrong.

**Comment by tshort** [comment]
Interesting. Good tip, @jpsamaroo. Will look into that some more because tests pass locally on Linux.
