### ISSUE TITLE
Godbolt support

### ISSUE THREAD

**Issue by PallHaraldsson** [tshort/StaticCompiler.jl#92]
Julia, as is, isn't supported at https://godbolt.org/

I don't know what the holdup is, but maybe this project should be there (too)?

https://github.com/compiler-explorer/compiler-explorer/issues/331

**Comment by brenhinkeller** [comment]
Would be cool to have! In principle, the native code generated by Julia and StaticCompiler should be the same, so if we can get Julia support there that should cover this too (since the staticcompilerable stuff is just a subset of all Julia)

**Comment by MasonProtter** [comment]
Julia is supported on godbolt now. Not sure why this package would be supported there though, I don't think that's a very reasonable or actionable goal. Is it okay if I close there @PallHaraldsson, or do you want it to stay open?

**Comment by PallHaraldsson** [comment]
I thought it would be easier for this, since they expect a compiler and some output, but I see it just works, more or less similar to what `@code_native` gives, so I'm ok with closing, not sure what further support would do here.
